[providers]
providers = ["node"]

[phases.setup]
dependsOn = ["base"]
pkgs = ["nodejs", "lua51", "lua51-bitop", "gcc"]

[phases.build]
dependsOn = ["setup"]
cmds = ["npm ci"]

[start]
cmd = "node index.js"
